apiVersion: v1
kind: Pod
metadata: 
   name: activity-pod
spec:
  containers:
    - name: activit-container
      image: ubuntu
      command: ['/bin/bash','-ec','cat /etc/app-data/application-data.properties /etc/secure-data/application-secure.properties']
      volumeMounts:
        - name: activity-configmap
          mountPath: /etc/app-data

        - name: activity-secret-vol
          mountPath: /etc/secure-data
  volumes:
    - name: activity-configmap
      configMap:
        name: my-app-data
    - name: activity-secret-vol
      secret:
        secretName: my-app-secret 


