apiVersion: v1
kind: Pod
metadata:
  name: cm-test
spec:
  containers:
    - name: cm-container
      image: busybox
      command: ["/bin/sh","-c","env"]
      envFrom:
        - configMapRef:
            name: my-website 
