apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - image: nginx
          name: nginx-container
  selector:
    matchLabels:
      env: prod

