apiVersion: apps/v1
kind: Deployment
metadata:
  name: count-user-visits
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: count-user-visits
          image: rk90229/count-user-visits

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: k8s-redis
        image: redis

---
apiVersion: v1
kind: Service
metadata:
  name: count-user-visits
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
    - port: 80
      targetPort: 30009

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    tier: backend
  ports:
    - port: 6379
      targetPort: 6379
